language: csharp
solution: StyleCop.Baboon.sln
install:
  - nuget restore StyleCop.Baboon.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release StyleCop.Baboon.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./StyleCop.Baboon.Tests/bin/Release/MyProject.Tests.dll
mono:
  - latest
